name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with g++
      run: make clean && make build
      env:
        EXTRA: -Werror
    - name: Build with clang
      run: make clean && make build
      env:
        EXTRA: -Werror
        CXX_TOOL: clang